# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'
tap 'stripe/stripe-cli'
tap 'cloudflare/cloudflare'

# Binaries
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'bat' # Used for spatie/visit
brew 'coreutils' # Those that come with macOS are outdated
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'gnupg'
brew 'grep'
brew 'httpie'
brew 'jq'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'multitail'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'stripe/stripe-cli/stripe'
brew 'stripe/stripe-mock/stripe-mock'
brew 'svn' # Needed to install fonts

# Spatie Medialibrary
brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'

# Development
brew 'go'
brew 'php'
brew 'php@8.0'
brew 'php@7.4'
brew 'composer'
brew 'imagemagick'
brew 'meilisearch'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'nvm'
brew 'redis'
brew 'yarn'
brew 'python@3.10'
brew 'ansible'
brew 'libssh2'
brew 'curl'
brew 'dnsmasq'
brew 'kubernetes-cli'
brew 'minikube'
brew 'moreutils'
brew 'openssh'
brew 'tree'
brew 'cloudflare/cloudflare/cloudflared'

# Apps
cask '1password'
cask '1password-cli'
cask 'caffeine'
cask 'chromium'
cask 'cloudflare-warp'
cask 'dbngin'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'gpg-suite'
cask 'helo'
cask 'imageoptim'
cask 'insomnia'
cask 'ngrok'
cask 'notion'
cask 'pastebot'
cask 'phpmon'
cask 'phpstorm'
cask 'postman'
cask 'ray'
cask 'screenflow'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'teamviewer'
cask 'telegram-desktop'
cask 'tor-browser'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'transmit'
cask 'tunnelbear'
cask 'tuple'
cask 'visual-studio-code'
cask 'vlc'
cask 'warp'
cask 'whatsapp'
cask 'zoom'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'

# Mac App Store
mas 'Giphy Capture', id: 668208984
mas 'Keynote', id: 409183694
mas 'Spark', id: 1176895641
